### ISSUE TITLE
Cryblend v5.1 Release

### ISSUE THREAD

**Issue by feedbackex** [travnick/CryBlend#124] opened 2015-07-08 21:00 UTC
![cryblendlogo_51_second_pose](https://cloud.githubusercontent.com/assets/12111733/14507827/3acf053a-01cd-11e6-89db-bf7a4798d7f3.jpg)

#### Compatibility:
* Only compatible with CryEngine 3.5 and up.
* Only compatible with Blender 2.7 and up.
* Supports primary assets: CGF, CGA, CHR, SKIN, ANM, I_CAF.

#### UI Changes:
* Apply Scale Animaiton.
* Edit Inverse Kinematics panel in Bone Utilities.
* Do materials and fix weight default were set to false in export menu.
* Add Property is changed with User Defined Properties menu.

#### New Features:
* Skeleton Physic.
* New Inverse Kinematics Bone Panel in Bone Utilities.
* Cycles render material support.
* Completely new interactive User Defined Property system.
* Added apply rotation and scale for skeleton that have animation without break bone.
* Delete .animsettings, .caf, .$animsettings files if there are exist for clean reexport animation.
* Set main material name which show in cryengine.
* Change selected material physic in Do Material panel.
* Remove unused vertex groups for selected mesh from vertex groups menu.

#### Improvements/Fixes:
* Texture export fix.
* Skeleton Animaiton.
* Blender 2.74 and up Skeleton and Animation support.
* Now bone names replace double underscore with whitespace like maya.
* CGF file is processed one time by rc.

**Comment by ochounos** [comment] 2016-02-14 14:45
Export animation is not working properly. When export i_caf files, with a skeleton with space in bone name; in .dae file in the tag animation and tag channel target is referencing the bone name whithout space management.

To solve the problem the next code must be added to __get_animation_location (line 863 export.py):

`        name = object_.name`
`        if "__" in name:`
`            bone = object_.name`
`            bone = bone.replace("__", "*")`
`            name = "{!s}{!s}{!s}".format(object_.name, "%Armature%--PRprops_name=", bone)`

`        target = "{!s}{!s}{!s}".format(name, "/translation.", axis)`

The funcion _get_animation_rotation (line 875 export.py) must patched too:

`        name = object_.name`
`        if "__" in name:`
`            bone = object_.name`
`            bone = bone.replace("__", "*")`
`            name = "{!s}{!s}{!s}".format(object_.name, "%Armature%--PRprops_name=", bone)`

`        #target = "{!s}{!s}{!s}{!s}".format(object_.name,`
`        target = "{!s}{!s}{!s}{!s}".format(name,`
`                                           "/rotation_",`
`                                           axis,`
`                                           ".ANGLE")`

After that, the channel is recognized and the bone included in the animation.
Note: in the code you must replace %Armature% with `'%{!s}%'.format(skeleton_name)` but I don't know how to do it.

Thanks.

**Comment by ochounos** [comment] 2016-02-14 15:49
When a proxy is added, for some reason the transformations are not applied. If when export you don´t choose apply transformations, the proxy generates an error. You can apply transformations to the proxy and everything works. I don't know how to force it in the code, in __add_proxy in __init_py line 305.

Also the name of the material is physProxyNone and should be physProxyNoDraw. 
The line 322 in _init_.py should be replaced by:

`        name = "{}__physProxyNoDraw".format(bound_box.name)`

Or maybe this format is managed in any other place?

**Comment by feedbackex** [comment] 2016-02-14 19:07
Hi @ochounos, I understand that problem just exist when skeleton have space. Is that right?

**Comment by ochounos** [comment] 2016-02-14 19:14
Hi @feedbackex Yes, you are right, that's the reason that I have added `if "__" in name:`.
I'm really sorry that I don't have experience with python, so I know what is not working but I don't know how to solve it. Let me know if I can help you with files or samples.

**Comment by feedbackex** [comment] 2016-02-14 19:36
Ok @ochounos, I have missed that situation, I will solve it whenever I have time.
Thank you for reporting.

About material, I have not looked new auto material system yet.

**Comment by ochounos** [comment] 2016-02-14 19:39
Thank you. Let me know if you need some feedback on it. With this code is working for me, I'm sure you can improve it.

About the material, in fact it's the physics, it's just change the string. Also could be good to apply transofrmations of the proxy, I don't know how to do it.

Thank you!

**Comment by ochounos** [comment] 2016-02-16 18:26
Both bugs should be fixed now in the pull request #146

**Comment by ochounos** [comment] 2016-03-24 06:32
To summarize, what tasks are missing to release this version?

- Finish webpage
- Add tutorials (text, video, downloadable samples)
- Finish documentation (wiki and/or pdf on web)
- Close all the pending issues (#98, #100, #180)
- Create a changelog

Is it possible to finish everything in a week? Issues can be closed, I can work on some samples and text tutorials, I think Daniel is working on webpage already.

I think we did a lot of work and people has been waiting too long to enjoy all the new features and bug fixes. Please, add everything that you think we are still missing in this list.

**Comment by SalahAdDin** [comment] 2016-03-26 03:26
:+1:

**Comment by motorsep** [comment] 2016-03-26 03:29
So, is it compatible (and tested) with CryEngine V then ?

**Comment by ochounos** [comment] 2016-03-26 05:57
I'm testing with Blender 2.77 and CryEngine V and it works. It's also compatible with LumberYard.

**Comment by SalahAdDin** [comment] 2016-03-26 23:24
Thank you very much!

**Comment by ochounos** [comment] 2016-04-02 18:24
@dwhite4 @feedbackex 

I ask again, can we release the 5.10 version already? What are we missing?

**Comment by dwhite4** [comment] 2016-04-02 20:03
We can release very soon, I just @feedbackex to merge is remove unused vertex groups issue.  And I would like all texture bugs to be worked out.  That's issues #182 and #185.

**Comment by feedbackex** [comment] 2016-04-03 05:26
Yes, we can release after those issues.

@ochounos, @dwhite4, could you add your improvement or fixes at that issue head with edit comment for history consistency.

**Comment by ochounos** [comment] 2016-04-03 08:24
I have provided a patch for #182 already. The issue #185 is not a bug but a new functionality and there is no pull request to review.
The changelog must be reviewed, not only in this issue but in the changelog.md file in the repository.

What about website? I don't have any access to web code, facebook page or old pdf manual document. Who is in charge on it? How is going with the changes needed?

**Comment by dwhite4** [comment] 2016-04-04 05:25
The website is mostly done, I eventually would like an official YouTube channel for CryBlend where we can put updated tutorials and these can be linked to the website.  The only thing missing on the website really is the donate button, which Elisha and I are working out.  Don't worry about the website for now though, we can always release without it.  It is technically already public.

Regarding the Facebook age, I am an editor but Mikolaj is the administrator.  If you would like access to editing the page (or to be able to comment as CryBlend), I can ask him to add you.  Just let me know.

As far as the PDF manual goes, this is just out of date.  You can update it if you feel like it, but it is entirely up to you.  I would like to update it at some point.

**Comment by ochounos** [comment] 2016-04-04 06:30
About the **web:** tutorials are old and maybe don't apply anymore, the "about" page is outdated and there is no way to contact with the team, only github but no emails, not everybody has github account.
I don't use **facebook,** just keep synchronized with latest changes.
The **pdf** should be reviewed, updated and added to the webpage. I don't have the doc, only not editable pdf document.
We should add to the repo and web a few **sample files** with all the functionality supported.

**Closed** 2016-04-19 23:24 UTC
Labels: Feature
