### ISSUE TITLE
Some small issues

### ISSUE THREAD

**Issue by dwhite4** [travnick/CryBlend#100] opened 2015-02-08 05:54 UTC
CryBlend improperly handles the following:
- Vertex groups.
- Excess/Unlinked Armature modifiers.
- Vertices with 8+ bone references.
- Bone structure should be taken from EDIT bones not POSE bones.

**Comment by ochounos** [comment] 2016-03-09 08:48
What is the current status of this one year old issue?

**Comment by dwhite4** [comment] 2016-03-12 00:17
These problems still exist but they have no detrimental impact on export.  They should be fixed at some point but are low priority.

**Comment by ochounos** [comment] 2016-03-12 07:19
Could you add more info about exactly what is the problem with first two? Third one seems fixed with export option "Fix weights". Last one is clear for me.
Maybe I could have a look.

**Comment by dwhite4** [comment] 2016-03-13 04:59
(1) When you delete a skeleton after performing weighting, the old vertex groups remain on the character mesh.  These residual groups can cause export errors.
(2) Similarly, when you delete a skeleton after performing weighting, the armature modifier remains on the character mesh, which will cause similar export issues.
(3) This is not handled by "Fix weights" yet.  "Fix weights" only fixes underweight/overweight vertices.  Each bone is still allowed to have infinitely many bone references, although I believe CE now allows up to 8 bone references.

**Comment by ochounos** [comment] 2016-03-14 09:06
Thank you Daniel, I don't have much time this week, but I will try to have a look.

**Comment by dwhite4** [comment] 2016-03-14 18:01
Cool, thanks for taking a look at these.

**Comment by ochounos** [comment] 2016-03-19 09:29
@dwhite4 @feedbackex 
First issue happens when a vertex has two weights defined. It can be reproduced creating two vertex groups and assigning weight to the same vertex in both groups. Collada file will have 2 weights for this vertex, but rc.exe doesn't accept two weights per vertex. This controller will be discarded and then the final skin will not be properly generated.

How to proceed?

- Ignore subsequent weights and process only the first one.
- Throw error and abort the export process.
- Sum all weights and calculate average. Assign  the weight to the vertex.

Any other idea?

**Comment by feedbackex** [comment] 2016-03-19 11:26
I think, throw error and abort the export process. User must very well know what is exported.

**Comment by ochounos** [comment] 2016-03-19 11:36
I think so too. I was thinking about some "validation scene" function that can run before export and report all the problems in the scene. There is some idea about it in the past. With this intermediate menu we can offer clear information about what is wrong and not just a few words on the top that is dissapearing.

**Comment by ochounos** [comment] 2016-03-19 11:37
Second issue, I cannot reproduce it. If I delete the skeleton, the armature modifier is still there but not assigned to any skeleton. It's not generating a problem for me. Anyway the vertex groups of the skeleton are kept and, if they refer to any vertex and weight it, it's generating problems again.

**Comment by dwhite4** [comment] 2016-03-19 18:10
I agree, I think throwing an error is the best option.  Also, regarding the second issue, I believe I have already fixed this in past commits.  This used to be an issue where information was taken from armature modifiers instead of the armature directly.  But I redesigned it so that information is taken from the armature.

**Comment by ochounos** [comment] 2016-03-22 11:33
I made a pull request to fix these problems #181 

1) Such vertex groups are ignored now, also groups with zero weight
2) Was fixed in other commit I suppose
3) Fixed to 8, ignore rest of groups and shows a warning
4) Was fixed in other commit I suppose

Alsoadded to manage different contexts when exporting, i.e. if you are in pose mode.

When the related pull request is reviewed i commited, we could close this issue.

**Comment by ochounos** [comment] 2016-03-29 06:30
Issues fixed on pull request #181 
No problems reported, can be closed.

**Closed by ochounos** 2016-03-29 06:30 UTC
Labels: Bug, Cleanup
